### ISSUE TITLE
Sponge is a C program

### ISSUE THREAD

**Issue by laurivosandi** [stigtsp/moreutils#1]
Looks like there is no way to trivially publicly comment on @joeyh site, so I'll just leave it here: I think it's completely bonkers that sponge is implemented as a C program. It's literally shell twoliner if you omit all the overengineering:

```
cat > $1.part
mv $1.part $1
```
Ironically enough in the C code there is a fallback that breaks atomic update, which is the reason you would use sponge in the first place: https://github.com/stigtsp/moreutils/blob/master/sponge.c#L374

**Comment by joeyh** [comment]
Plenty of people email me patches and suggestions for moreutils. My
email address is in the README. This is generally what one is expected
to do to contact the author of a program, unless there is some obvious
link to a bug tracking system or website or whatever to use.

Mentioning me in a random clone of a repository on a random git hosting
site is unfortunately not going to result in a substantive discussion.
Sorry.

-- 
see shy jo
